#!/bin/sh

echo 'Checking if Jetty is already installed...'
if [ -d ~/jetty ]
then
    echo 'Jetty found.'
else
    echo 'Jetty not found. Installing it...'
    curl http://dotcloud-plugins.s3.amazonaws.com/jetty-distribution-8.1.3.v20120416.tar.gz |
        tar -C ~ -zxf-
    ln -s jetty-distribution-8.1.3.v20120416 ~/jetty
    echo 'Disabling test.war...'
    rm -f ~/jetty/webapps/test.war
    echo 'Jetty installed.'
fi

echo 'Checking if Solr is already installed...'
if [ -d ~/solr ]
then
    echo 'Solr found.'
else
    echo 'Solr not found. Installing it...'
    curl http://dotcloud-plugins.s3.amazonaws.com/apache-solr-3.6.0.tgz |
        tar -C ~ -zxf-
    ln -s apache-solr-3.6.0 ~/solr
    echo 'Solr installed. Copying WAR to webapps directory.'
    cp ~/solr/dist/apache-solr-3.6.0.war ~/jetty/webapps/ROOT.war
fi

mkdir -p ~/data

echo 'Installing Solr config...'
cp -a solr/config/. ~/data/solr

echo 'Installing run script...'
cp solr/run ~

echo 'Build complete.'
